apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
  namespace: gov-scheme-navigator
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: scraper
              image: gov-scheme-navigator-backend:latest
              imagePullPolicy: IfNotPresent
              command: ["scrapy", "crawl", "myscheme"]
